import { getSupabase } from '@/services/supabase';
import type { Address } from '@/types';

const SELECT = 'address_id,label,recipient_name,recipient_phone,delivery_instructions,is_default,addresses!inner(id,address_line_1,address_line_2,neighborhood,municipality,city,province,country_code,location)';
type Row = {address_id:string;label:string;recipient_name:string|null;recipient_phone:string|null;delivery_instructions:string|null;is_default:boolean;addresses:{id:string;address_line_1:string;address_line_2:string|undefined|null;neighborhood:string|undefined|null;municipality:string|undefined|null;city:string;province:string;country_code:string;location:string}|{id:string;address_line_1:string;address_line_2:string|undefined|null;neighborhood:string|undefined|null;municipality:string|undefined|null;city:string;province:string;country_code:string;location:string}[]};
function parseLocation(location:string|unknown) { if(typeof location !== 'string') return undefined; const m=location.match(/POINT\s*\(\s*([-\d.]+)\s+([-\d.]+)\s*\)/i); if(!m) return undefined; return {latitude:Number(m[2]),longitude:Number(m[1])}; }
function map(row:Row):Address { const a=Array.isArray(row.addresses) ? row.addresses[0] : row.addresses; if(!a) throw new Error('Endereço não encontrado.'); return {id:a.id,label:row.label,line:[a.address_line_1,a.neighborhood,a.city].filter(Boolean).join(', '),current:row.is_default,coordinates:parseLocation(a.location),province:a.province,municipality:a.municipality ?? undefined,city:a.city,neighborhood:a.neighborhood ?? undefined,deliveryInstructions:row.delivery_instructions ?? undefined}; }
export function createSupabaseLocationRepository(){
 const sb=getSupabase(); let addresses:Address[]=[];
 async function reload(){ if(!sb) throw new Error('Supabase não configurado.'); const {data,error}=await sb.from('customer_addresses').select(SELECT).order('is_default',{ascending:false}).order('created_at'); if(error) throw error; addresses=(data??[] as unknown as Row[]).map(map); }
 return { initialize: reload, listAddresses(){return addresses.map(a=>({...a}));}, getDefaultAddress(){return addresses.find(a=>a.current)??addresses[0]??null;},
  async addAddress(address:Address){ if(!sb||!address.coordinates) throw new Error('A localização exata é necessária para entregar.'); const {data,error}=await sb.rpc('create_customer_address',{p_label:address.label,p_address_line_1:address.line,p_neighborhood:address.neighborhood??null,p_municipality:address.municipality??null,p_city:address.city ?? address.municipality ?? 'Luanda',p_province:address.province??'Luanda',p_latitude:address.coordinates.latitude,p_longitude:address.coordinates.longitude,p_delivery_instructions:address.deliveryInstructions??null}); if(error) throw error; await reload(); return addresses.find(a=>a.id===data)??addresses[0]; },
  async setDefault(id:string){if(!sb) throw new Error('Supabase não configurado.'); const {error}=await sb.rpc('set_default_customer_address',{p_address_id:id}); if(error) throw error; await reload(); return true;},
  async removeAddress(id:string){if(!sb) throw new Error('Supabase não configurado.'); const {error}=await sb.rpc('remove_customer_address',{p_address_id:id}); if(error) throw error; await reload(); return true;},
  async updateAddress(id:string,changes:Partial<Omit<Address,'id'>>){if(!sb) throw new Error('Supabase não configurado.'); const {data,error}=await sb.rpc('update_customer_address',{p_address_id:id,p_label:changes.label??null,p_address_line_1:changes.line??null,p_neighborhood:changes.neighborhood??null,p_delivery_instructions:changes.deliveryInstructions??null}); if(error) throw error; await reload(); return addresses.find(a=>a.id===data)??null;}
 };
}
